import { Component, inject, Input, OnInit } from '@angular/core';
import { IonCard, IonCardHeader, IonCardTitle, IonCardContent, IonCardSubtitle, IonIcon, IonButton } from "@ionic/angular/standalone";
import dayjs from 'dayjs';
import { DateService } from 'src/app/services/dates/date-service.service';
import { ListItem } from 'src/app/types/interfaces';

@Component({
  standalone: true,
  selector: 'app-list-item',
  templateUrl: './list-item.component.html',
  styleUrls: ['./list-item.component.css'],
  imports: [IonCard, IonCardHeader, IonCardTitle, IonCardContent, IonCardSubtitle, IonIcon]
})
export class ListItemComponent  implements OnInit {
  //**
  // The listItem will be defined when the component is generated by the ListComponent */
  @Input()
  public listItem!: ListItem;

  private dateService = inject(DateService);

  constructor() { }

  ngOnInit() { }

  onClick() {
    console.log(`You clicked on ${this.listItem.title}`);
  }

  formatDate() {
    if (this.listItem.date === undefined)
      return null;
    return this.dateService.format(this.listItem.date, 'MM/DD/YYYY');
  }
}
